### ISSUE TITLE
Tasmanian fails to find BLAS with IBM XL compiler

### ISSUE THREAD

**Issue by luszczek** [xsdk-project/xsdk-issues#101]
When running CMake for Tasmanian, `sgemm_` symbols is not found and configuration fails:

```log
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for sgemm_
-- Looking for sgemm_ - not found
CMake Error at /autofs/nccs-svm1_sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/cmake-3.15.2-xit2o3iepxvqbyku77lwcugufilztu7t/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find BLAS (missing: BLAS_LIBRARIES)
```

**Comment by mkstoyanov** [comment]
Hey Piotr, you have to use @mkstoyanov when you open those issues, otherwise I don't see them. I don't have any kind of notification for this.

For this issue, spack is supposed to pull in and compile OpenBLAS. If CMake cannot find it, it means it didn't compile or spack didn't set the correct variables. 

Are you sure it is related to the compiler? Was OpenBLAS build with the project?
