### ISSUE TITLE
dealii, phist compatibility with trilinos - Tpetra  GO=int vs long

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#104]
Currently with spack@develop - i.e deaill@develop+trilinos@develop - I get:
```
dealii requires trilinos variant gotype=int, but spec asked for gotype=long
```
Some related discussion is at https://github.com/spack/spack/pull/14215

There is also a mention of phist in the above link - but currently I get error when resolving dealii + trilinos dependency.

**Comment by jwillenbring** [comment]
CC: @trilinos/tpetra

@balay The underlying issue here is the that Tpetra deprecated and removed some features. Here is the relevant part from the deprecation announcement:

Packages: Trilinos-wide next generation stack

Deprecation: Explicit instantiation of multiple different global ordinal types and multiple different local ordinal types

Mitigation: Use default global ordinal type long long and local ordinal type int, or specify to CMake -DTpetra_INST_INT_IN=ON to use global ordinal type int and local ordinal type int.

Justification: Building with multiple ordinal types increases build times and library sizes; all applications surveyed used only one global ordinal type.

@bangerth What is the right way to proceed? One possibility would be for dealii to use gotype=long. We could also look at setting gotype=int, but that has the significant disadvantage of moving away from the new default for all of xSDK, which I fear could be a mistake.

**Comment by jthies** [comment]
I don't think this is a phist issue. xSDK will have to decide which index type makes most sense (and personally, I think problems smaller than 2B unknowns are not extreme-scale). Phist, I think, uses 64-bit global integers with Tpetra by default, but we can switch this by a cmake flag.

**Comment by balay** [comment]
> xSDK will have to decide which index type makes most sense 

Yes - I'm not sure if it would be possible to buid xsdk (in single step] if different packages have different choices for this option.

 The suggestion for this case was to build trilinos twice to satisfy each of the packages using different value for `gotype` - but I doubt spack allows this [in a single dependency tree].

**Comment by jwillenbring** [comment]
> The suggestion for this case was to build trilinos twice to satisfy each of the packages using different value for gotype - but I doubt spack allows this [in a single dependency tree].

No, it doesn't. Multiple copies could be kept in the same build cache, but we cannot have a single interoperable ecosystem in this way.

**Comment by jthies** [comment]
what about adding a global "int64" variant to xSDK? If set, packages that need to decide (like Trilinos) will set the respective option, and others that can't follow it (dealii here) will have to cut the link.

**Comment by bangerth** [comment]
I don't recall what exactly we decided within deal.II, though we debated the issue. By default, deal.II uses 32-bit indices and then uses the corresponding 32-bit data type for Trilinos indices as well. But it can be configured to use 64-bit indices as well, and then uses the 64-bit Trilinos index types.

So the problem appears to be that deal.II is configured with the default (-> 32 bit indices for Trilinos) whereas phist requires the 64-bit Trilinos. My personal opinion is that the Trilinos decision is quite unfortunate for a library so far down in the stack because it will inevitably lead to people having to install multiple versions of Trilinos on their systems (think of how supercomputing centers will have to handle this). But it wasn't my decision to make and it is what it is. (deal.II of course made the same decision, albeit at a higher level in the stack.)

So there are two options: (i) xsdk builds Trilinos twice, once for each index type, and phist and deal.II just link against different versions. (ii) deal.II in xSDK is configured with 64-bit indices. The latter might minimize the technical pain and so would be my suggestion.

@Rombur @davydden @tamiko: Any opinions?

**Comment by Rombur** [comment]
> deal.II in xSDK is configured with 64-bit indices. The latter might minimize the technical pain and so would be my suggestion.

That won't fix the problem. The issue is that MueLU does not provided all the Epetra interfaces when Tpetra is using long. What we decided to do was to have the MueLU dependency in deal.II optional (https://github.com/dealii/dealii/pull/9237). We need to add a variant in spack that reflects that MueLU is not required anymore and we need to disable MueLU when using xSDK.

**Comment by bangerth** [comment]
Ah, that's right :-( How do we go about this? Just add another deal.II configuration switch?

**Comment by Rombur** [comment]
Yes, that's probably the easiest thing to do.

**Comment by balay** [comment]
Personally - I think xsdk should expose the `64-bit indices` as variant - and all packages that can support this option can expose this variant [i.e wrt current packages dependencies would work in both modes `xsdk+int64` and `xsdk~int64`]

Wrt `MueLU does not provided all the Epetra interfaces when Tpetra is using long` perhaps trilinos can address this issue.

I think xsdk using dealii~muelu should be fine [for this release]

**Comment by bangerth** [comment]
On 4/13/20 10:18 AM, Satish Balay wrote:
> Wrt |MueLU does not provided all the Epetra interfaces when Tpetra is using 
> long| perhaps trilinos can address this issue.

Yes, this is really unfortunate. I believe that it's a regression.

**Comment by Rombur** [comment]
> Wrt MueLU does not provided all the Epetra interfaces when Tpetra is using long perhaps trilinos can address this issue.

We talked to them about it and they said that they won't fix this.

**Comment by jthies** [comment]
I think we missed a crucial point here - I just found that "long" is "at least 32 bits", and "int" is "at least 16 bits". So I think it would make things more portable if Trilinos provided gotype=int32_t|int64_t instead. As for the phist/dealii issue: we can probably agree on "long" for now (the default for the trilinos package). The global "int64" variant would also be portable because then the packages have o make sure they use a 64-bit integer type like int64_t for global indices

**Comment by jthies** [comment]
With this PR, phist offers an "int64" variant and checks the Trilinos spec for ompatibility:
https://github.com/spack/spack/pull/16209
It still requires gotype=long for the ~int64 varian up to now

**Comment by jthies** [comment]
I now updated the spack PR mentioned above to use ^trilinos gotype=int if phist~int64 is requested.
@balay, could you try specifying in the spack package "trilinos gotype=int" and "phist@1.9.0 ~int64" (plus whatever other variants are set already). This should be compatible with the requirements fo dealii. But I still think that xSDK should have an int64 variant itself.

**Comment by keitat** [comment]
As far as I know, Trilinos team is not planning to add new capabilities to the first generation (old C++) Trilinos packages (those dependent on Epetra).  Most new features will be developed in the second generation packages, which exploit the modern C++ features (and use Tpetra and Kokkos).  It is technically possible to integrate Epetra64 and MueLu with some engineering effort, but it is going to be a short-term solution as we are not planing to add any new capabilities to Epetra (such as accelerators and new backend runtime support).
