### ISSUE TITLE
deal.ii fails to build on LLNL Lassen (POWER9)

### ISSUE THREAD

**Issue by balos1** [xsdk-project/xsdk-issues#132]
`spack install -j40 xsdk%gcc@7.3.1 ^spectrum-mpi ^openblas@0.3.5`

* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le

I get a bunch of errors like this:

```
  >> 30282    source/numerics/CMakeFiles/obj_numerics_release.dir/fe_field_function.cc.o:fe_field_function.cc:function dealii::Functions::FEFieldFunction<2, dealii::DoFHandler<2
              , 2>, dealii::Vector<double> >::vector_gradient_list(std::vector<dealii::Point<2, double>, std::allocator<dealii::Point<2, double> > > const&, std::vector<std::vec
              tor<dealii::Tensor<1, 2, double>, std::allocator<dealii::Tensor<1, 2, double> > >, std::allocator<std::vector<dealii::Tensor<1, 2, double>, std::allocator<dealii::
              Tensor<1, 2, double> > > > >&) const: error: toc optimization is not supported for 0xe7ea0002 instruction
```

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5503921/spack-build-out.txt)

**Comment by bangerth** [comment]
@balos1 Oof. That's a really unfortunate error. I had to google for that. I *think* what is happening is that the compiler is telling us that some optimization it's trying to perform isn't going to work here, but instead of just printing this as a note, it prints it as a warning. Because we use `-Werror` to compile deal.II, this gets upgraded to an error and the whole thing falls on its face. 

To confirm this, can you compile with `make VERBOSE=ON` and copy-paste the invocation of the compiler where it tried to compile one of these files, along with the error that command produces? You might want to run it with `make -jX` first, and then `make -j1 VERBOSE=ON` so that you get compiler command line and error right next to each other for the first file that fails.

@tamiko FYI

**Comment by balos1** [comment]
@bangerth Here is the log when building with `spack install -v -j1` (effectively `make -j1 VERBOSE=ON`).

[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/5519513/spack-build-out.txt)

**Comment by bangerth** [comment]
Hm, there is no `-Werror`: The linker unconditionally errors out when it can't optimize something. That's poor style. The gold people fixed this a while ago and downgraded it to a warning (which I think is still poor style): https://sourceware.org/legacy-ml/binutils/2017-01/msg00139.html

Given that there is really nothing at all that we can do about this, the only idea I have is to disable the use of gold as the linker. @balos1 -- would you be willing to try running the last command in your log file (requiring quite a lot of copy-paste) with and without the use of the `-fuse-ld=gold` flag, and see whether that fixes the problem?

**Comment by PhilMiller** [comment]
> Given that there is really nothing at all that we can do about this, the only idea I have is to disable the use of gold as the linker. @balos1 -- would you be willing to try running the last command in your log file (requiring quite a lot of copy-paste) with and without the use of the -fuse-ld=gold flag, and see whether that fixes the problem?

Not working with deal.ii, but GOogle led me here for the same problem, and switching away from gold to ld as suggested worked for me.
