### ISSUE TITLE
strumpack-7.0.0 build failure with intel-19

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#184]
https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3161006152
```
 >> 171    /nfs/apps/spacks/2022-02-10/opt/spack/linux-centos7-x86_64/gcc-7.3.
            0/gcc-9.2.0-llib7puyqxdfte5dd2mw33v7d6mjarrw/include/c++/9.2.0/tupl
            e(553): error: pack "_UElements" does not have the same number of e
            lements as "_Elements"
     172      	    __and_<is_nothrow_assignable<_Elements&, _UElements>...>::va
            lue;
...
```
[spack-build-out(3).txt](https://github.com/xsdk-project/xsdk-issues/files/9766706/spack-build-out.3.txt)

**Comment by pghysels** [comment]
Can you try 7.0.1, which I just created?

STRUMPACK 7.0.0 was requesting C++17, but C++14 should be enough. (some code requiring C++17 was removed again)
The problem seems to be gone when using C++14.

This seems like a known incompatibility between newer gcc headers and the intel compiler, see for instance:
- https://github.com/xtensor-stack/xtensor/issues/2191
- https://bitbucket.org/berkeleylab/upcxx/issues/302/build-failure-for-intel-c-with-std-c-17
- https://gitlab.com/gromacs/gromacs/-/issues/3905

**Comment by balay** [comment]
Thanks! The build with intel-19 goes through now with 7.0.1

With more pkgs starting to require cxx-17 - I think we'll also have to migrate to newer Intel compilers for xsdk CI in the near future..

**Comment by balos1** [comment]
Based on the comment above from @balay, this seems to be fixed, so I am closing. Reopen if it persists.
