### ISSUE TITLE
mfem + shared build failures

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#199]
Noticed mfem was defaulting to a static build - attempted to enable `mfem+shared` - most builds are failing here..

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/3253841202

**Comment by v-dobrev** [comment]
Thanks for reporting this issue.

This happens because the installation of miniapps (`+miniapps` variant which is enabled by default in xSDK) is not supported by the MFEM build system natively, so we use a hack in the Spack package that fails with `+shared`. This seems to affect just one miniapp: `hooke`.

I'll try to address this in https://github.com/spack/spack/pull/33603 but I'm not sure this is that important for the xSDK release where MFEM is built just static by default.

@balay, do you think it is important to resolve this for the xSDK release?

**Comment by balay** [comment]
> @balay, do you think it is important to resolve this for the xSDK release?

Its not critical - we had static mfem in earlier releases. It just felt odd to have this built as static 

[since the discussion in the other kokkos issue was about shared vs static libraries]

**Comment by v-dobrev** [comment]
This issue should now be resolved in https://github.com/spack/spack/pull/33603.

**Comment by balay** [comment]
Thanks! enabling mfem+shared now

https://gitlab.com/xsdk-project/spack-xsdk/-/pipelines/685829508

**Comment by v-dobrev** [comment]
Note that https://github.com/spack/spack/pull/33603 has a small tweak for HYPRE too. This is to allow building HYPRE + ROCm with external (to Spack) ROCm installation.

**Comment by balay** [comment]
Closing as `mfem+shared` works now.
