### ISSUE TITLE
PHIST compatibility with policy M1

### ISSUE THREAD

**Issue by balos1** [xsdk-project/xsdk-issues#78]
In the posted [compatibility document](https://github.com/xsdk-project/xsdk-policy-compatibility/blob/master/phist-policy-compatibility.md), PHIST is listed as only partially compliant with M1. The issue at hand is whether it is required that they provide `TPL_<package>_*` flags even though what TPLs can be enabled depends on what kernel is used. 

>TPL_ENABLE_<PACKAGE>. Which TPL's are supported by phist depends on the kernel library. For instance, with the builtin kernels one cn use ParMETIS for repartitioning, with Epetra onee can use Isorropia. PHIST therefore has flags like PHIST_USE_GRAPH_TPLS, which means: check if you can find ParMETIS or whatever you support given the kernel library.

My interpretation of the policy leads me to the conclusion that PHIST should provide the  `TPL_<package>_*` options and just conditionally disable them in CMake if the required kernel is not used.

@jthies 
@jwillenbring 
@balay

**Comment by jthies** [comment]
Hi Cody,

thanks for reviewing/commenting. I think I can implement it the way you suggest, I'll need a couple of days, though. This concerns quite a few TPLs, especially if I have to provide the option for each Trilinos package separately (e.g. TPL_EpetraExt_LIBRARIES,...). Obviously Trilinos has its Tribits package for this, but is there a convenient way I can implement short of switching ot Tribits myself?

And another thought: once I've done so, I'ld have to change my spack package to add all the variants as well, and pass the TPL_XYZ_LIBRARIES/INCLUDE_DIRS etc to CMake, rather than using find_package and assume that it's in the CMAKE_PREFIX_PATH?

**Comment by balos1** [comment]
I don't know if there is a more convenient way that would be fully compliant with the policy as written, and at the same time preserve the checks PHIST does to ensure only compatible TPLs can be enabled. As far as the Spack question. Yes, you would need to pass the TPL_XYZ_LIBRARIES/INCLUDE_DIRS to CMake doing things this way. 

Perhaps @keitat or @balay have a better suggestion about how to handle it.

I have advocated for changes to the xSDK CMake policies to allow for CMake packages to leverage CMake's find_package, as you have, in #71. If the policies allowed for this rather than strictly requiring the TPL_XYZ_LIBRARIES/INCLUDE_DIRS options then you could have an option `TPL_TRILINOS_DIR` which would be used to set the path to the Trilinos `lib/cmake` directory (and of course TPL_PARMETIS_LIBRARIES/INCLUDE_DIRS options since it is not a part of Trilinos). 

Then maybe you could just have TPL_ENABLE_XYZ options for the kernel options only and determine the correct packages to enable based on the kernel. You can pass the `TPL_TRILINOS_DIR` to CMake's find_package to be sure that the Trilinos packages you find are the correct ones. 

Of course, this method requires the policy change I suggest in #71 to be accepted.

**Comment by jthies** [comment]
I updated PHIST to accept the TPL_* flags now, and honor them as seems useful to me. For packages that provde a <pkg>-config.cmake or <pkg>.pc file I only accept TPL_<pkg>_DIR and report an error if TPL_<pkg>_LIBRARIES or _INCLUDE_DIRS are given. Rationale: I can't check if the values given make sense for me because I don't know how the package in any future version nhas to be linked. The policy in its current form asks me to do this, though. @balos1, is this sufficient for you? If so I would update the policy compatibility document.

**Comment by keitat** [comment]
As far as I know, Trilinos put all headers and archive files into centralized locations, respectively.   Can you list the Trilinos sub-pacakges (such as Epetra) PHIST is using?  I think XSDK's Trilinos build supports all you want.

**Comment by balos1** [comment]
PHIST was included in the v0.4.0 release of the xSDK. Also https://github.com/xsdk-project/xsdk-community-policies/pull/1 addresses the original problem brought up in this issue.
