### ISSUE TITLE
sundials: build failure on linux-centos7-mic_knl / intel@18.0.2

### ISSUE THREAD

**Issue by balay** [xsdk-project/xsdk-issues#86]
[spack-build-out.txt](https://github.com/xsdk-project/xsdk-issues/files/3796281/spack-build-out.txt)

**Comment by balos1** [comment]
CC @gardner48

**Comment by balay** [comment]
Update: reverting https://github.com/spack/spack/commit/9d8512173a57664fa71d509e4451bfe904dc9506 gets the build going..

Will check which part of this change is the trigger..

**Comment by balos1** [comment]
@balay The error is with SuperLU_DIST, but not exactly sure what it is yet. The patch removed the requirement of `gcc@6:` for the superlu-dist variant to be enabled with SUNDIALS, which is why this was not noticed before. So worst case, we should be able to keep that patch, but just re-add the `gcc@6:` requirement for the `superlu-dist` variant of SUNDIALS.

**Comment by balay** [comment]
ok - I can do this.

BTW: - my build with gcc-4.8.5 was fine [with +superlu-dist].

**Comment by balay** [comment]
Also - on a different box [the utk machine] - the build with intel-18.0.1 went through fine.

We can use this work-arround for this release - but I suspect the issue is somewhere else..

**Comment by balay** [comment]
I pushed this change

https://github.com/spack/spack/commit/d8b47b66c8e0c745e98a271f4c938c8c1401e611

**Comment by balos1** [comment]
Ill note everything built fine for me on Quartz at LLNL with intel-18.0.2, so I am not sure what the underlying problem is here. It seems the issue is just on Theta.

**Comment by balay** [comment]
Closing as we added the work-around [enable sundials+superlu-dist only on gcc6:]
