### ISSUE TITLE
Trilinos' DTK fails to compile Fortran bindings with IBM XL Fortran

### ISSUE THREAD

**Issue by luszczek** [xsdk-project/xsdk-issues#94]
Trilinos compilation fails for `DTK_Fortran_API.F90` with the following error:

```log
"spack-stage-trilinos-12.18.1-mpvrpgyrnnoghcnodo3sb75wux5f5mcs/spack-src/DataTransferKit/packages/Interface/src/DTK_Fortran_API.F90",
1513-083 (E) Internal or module function swig_result was not set within the
function.
"spack-stage-trilinos-12.18.1-mpvrpgyrnnoghcnodo3sb75wux5f5mcs/spack-src/DataTransferKit/packages/Interface/src/DTK_Fortran_API.F90",
1513-083 (E) Internal or module function swig_result was not set within the
function.
"spack-stage-trilinos-12.18.1-mpvrpgyrnnoghcnodo3sb75wux5f5mcs/spack-src/DataTransferKit/packages/Interface/src/DTK_Fortran_API.F90",
1516-044 (S) A conversion from type unknown is not permitted.
** datatransferkit   === End of Compilation 1 ===
1501-511  Compilation failed for file DTK_Fortran_API.F90.
make[2]: ***
[DataTransferKit/packages/Interface/src/CMakeFiles/dtk_interface.dir/DTK_Fortran_API.F90.o]
Error 1
```

**Comment by mkstoyanov** [comment]
Hey, has anyone been able to work around this?

I am getting the same problem with heFFTe when using the IBM XL compiler on Summit.

**Comment by mkstoyanov** [comment]
@sethrj @dalg24 Does either of you guys know a work around this one?

**Comment by aprokop** [comment]
> Hey, has anyone been able to work around this?
> 
> I am getting the same problem with heFFTe when using the IBM XL compiler on Summit.

@mkstoyanov Same as in you have a problem in your generated Fortran wrappers? Or in using DTK?

**Comment by dalg24** [comment]
Pretty sure it is the former.

**Comment by mkstoyanov** [comment]
It's in the generated wrappers for both heFFTe and DTK, but I don't know the work-around and I'm asking if you guys have found it.

**Comment by sethrj** [comment]
This does sound like an error in the SWIG wrappers, either in the SWIG generation (subtle standards violation that GCC is allowing) or a compiler bug in XL fortran (wouldn't surprise me). I fixed a few of both issues when I last tried building on Summit, but right now I can't seem to log on...

**Comment by mkstoyanov** [comment]
@sethrj I just installed the latest `spack install swig@fortran` and regenerated the bindings, but `diff` showed no difference. I'm sure this is a discrepancy in the Fortran standard between gfortran and  XL but how can we debug it?

**Comment by sethrj** [comment]
@mkstoyanov I'd start by configuring SWIG and running the fortran unit tests with `xlfort` instead of `gfortran`. The last time I tried on summit I had to do this:
```
ml xl boost
export CC=xlc; export CXX=xlc++; export FC=xlf2003
```
Then configuring swig uses XL correctly.

Can one of you send me an active OLCF account name that I can apply for? It looks like mine must've all expired because I can't log on to the head node anymore.

**Comment by sethrj** [comment]
Wellll guys I just spent half an hour debugging what I assumed was (E) for error, but it turns out I guess (E) means "not an error". Here's a minimal test case with summit xlf/16.1.1-5:
```fortran
module poops
contains
   subroutine get_stuff(fout)
      integer, allocatable :: fout(:)
      allocate(integer :: fout(10))
      fout(:) = 0
   end subroutine
   function doit() result(fresult)
      integer, allocatable :: fresult(:)
      call get_stuff(fresult)
   end function
end module
```
produces
```
$ xlf2003 -c -fpic -g allocatable-poop.f90
"poops.f90", 1513-083 (E) Internal or module function fresult was not set within the function.
** poops   === End of Compilation 1 ===
1501-510  Compilation successful for file poops.f90.
```
... but apparently that's not what's causing the failure, because it generates `poops.o` and `poops.mod`.

So maybe `(E)` is for "eh, maybe this is a bug" and `(S)` is for "sucks to be XLF"? I'll see if I can replicate the super-helpful diagnostic 
> 1516-044 (S) A conversion from type unknown is not permitted

**Comment by mkstoyanov** [comment]
```
Fatal Error: Something went right!
Please break your code and try again to correct the issue.
```
Now I have to figure out the real issue for failing to compile.

**Comment by sethrj** [comment]
Yeah so I guess (S) stands for severe -- I didn't see anything exactly like this in the SWIG unit tests. There were some failures due to multi-module imports, but I think DTK runs from a single module, so I'm not sure what's failing and I can't until I figure out how to build trilinos and DTK with XL just enough to get the failure message.

**Comment by mkstoyanov** [comment]
I finally figured this one out, so I'm posting here since this is the first Google hit when searching for the error message. @sethrj @mtlaiu

The short story, I added the following to the CMake build command:
```
-DCMAKE_Fortran_FLAGS=-qthreaded
```
which keeps the default `-qthreaded` and removes `-qhalt=e`, see the long explanation below.

The XL compiler blurs the distinction between "warning" and "error" by having categories of "error", "severe error", and "unrecoverable error". Much of what falls under the "error" category would be treated as a "warning" by other compilers.

XL uses the flag `-qhalt=<e,s,u>` to determine which level or "error" should halt the build process. By default, XL uses `-qhalt=s` for severe errors, but CMake overwrites that and sets `-qhalt=e` which is more or less equivalent to adding `-Werror` to the default GCC flags. The issue is with Fortran and does not seem to affect C++.
